name: First Workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list files
        run: ls

      - name: read file
        run: cat README.md
