name: Generate ASCII Text

on: push

jobs:
  build-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay
        run: sudo apt install cowsay -y
      
      - name: execute cowsay
        run: cowsay -f dragon "I am a dragon!" > dragon.txt
      
      - uses: actions/upload-artifact@v4
        with:
          name: dragon-text
          path: dragon.txt

  test-job-2:
    needs: build-job-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon-text

      - name: test if file exists
        run: grep -i dragon dragon.txt

  deploy-job-3:
    needs: test-job-2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon-text
      - name: Read file
        run: cat dragon.txt
      