name: Generate ASCII Text

on: push

jobs:
  build-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay
        run: sudo apt install cowsay -y
      
      - name: execute cowsay
        run: cowsay -f dragon "I am a dragon!" > dragon.txt
      
      - name: sleep for 30 sec
        run: sleep 30

  test-job-2:
    needs: build-job-1
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 10 sec
        run: sleep 10

      - name: test if file exists
        run: grep -i dragon dragon.txt

  deploy-job-3:
    needs: test-job-2
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat dragon.txt
      
      - name: deploy
        run: echo Deploying...
        