name: Matrix Strategy

on: [push]

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker details
        run: docker info
      
      - name: Run image on ${{ matrix.os }}
        run: docker run --rm ${{ matrix.images }}