name: Variables and Secrets

on: push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USER: melvincv
  IMAGE_NAME: vote-app

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    concurrency:
      group: docker-deploy
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image 1
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest ./app/vote

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ env.DOCKER_USER }} --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest